version: '3.9'
services:

  elasticsearch:
    container_name: elasticsearch-server
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      ELASTIC_PASSWORD: "admin123"
      xpack.security.enabled: "true"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq-dashboard
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    #    volumes:
    #      - ./seq-data:/data
    restart: unless-stopped

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    container_name: seq-gelf
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
      GELF_ENABLE_DIAGNOSTICS: "True"
    restart: unless-stopped

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-all
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
    restart: unless-stopped

  kafka-broker:
    # NOTE: Please use the latest version here!
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda
    ports:
      - "9092:9092"
      - "29092:29092"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    restart: unless-stopped

  kafka-console:
    image: docker.redpanda.com/vectorized/console:latest
    container_name: kafka-console
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      - kafka-broker
    restart: always
